development:
  cloud_name: "virgyldieulefet"
  api_key: "496185696264984"
  api_secret: "KtNjqhkRcNdzPCDpbjAPVndyJpk"
  secure: true
  cdn_subdomain: true
production:
  cloud_name: "virgyldieulefet"
  api_key: "496185696264984"
  api_secret: "KtNjqhkRcNdzPCDpbjAPVndyJpk"
  secure: true
  cdn_subdomain: true
